<div class="row">
    <div class="col-md-8">
        <form name="addData" method="post" id="addData" class="form" action="<?php echo $block->getUrl('faq/manage/save'); ?>"
              data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
              data-mage-init='{"validation":{}}' enctype = 'multipart/form-data'>
            <fieldset class="fieldset">
                <legend class="legend"><span><?= $block->escapeHtmlAttr(__('Ask your question')) ?></span></legend>
                <fieldset class="fieldset row">
                    <div class="fields col-md-6">
                        <div class="field name required">
                            <label class="label" for="title"><span><?= $block->
                                escapeHtmlAttr(__('Name')) ?></span></label>
                            <div class="control">
                                <input name="name" id="name" title="Name" value="" class="input-text" type="text"
                                       data-validate="{required:true, 'validate-alphanum-with-spaces':true}">
                            </div>
                        </div>
                        <div class="field name required">
                            <label class="label" for="title"><span><?= $block->escapeHtmlAttr(__('Question')) ?></span></label>
                            <div class="control">
                                <textarea  name="question" row="4" cols="50" id="question" title="Question" value="" class="input-text"
                                     type="textarea" data-validate="{required:true}"></textarea>
                            </div>
                        </div>      
                    </div>
                </fieldset>
            </fieldset>      
</div>

            <div class="actions-toolbar">
                <div class="primary">
                    <button type="submit" class="action submit primary" title="Submit"><span><?= $block->
                        escapeHtmlAttr(__('Submit')) ?></span></button>
                </div>
            </div>
        </form>
    </div>
</div>